FREQUENCY_TERMS = {
    "very common": {"very common", "≥1/10", "≥ 1/10", ">10%", "> 10%"},
    "common": {"common", "≥1/100", "≥ 1/100", "≥1/100 to <1/10", "1-10%"},
    "uncommon": {"uncommon", "≥1/1,000", "≥ 1/1,000", "≥1/1,000 to <1/100", "0.1-1%"},
    "rare": {"rare", "≥1/10,000", "≥ 1/10,000", "≥1/10,000 to <1/1,000", "0.01-0.1%"},
    "very rare": {"very rare", "<1/10,000", "< 1/10,000", "<0.01%"},
    "not known": {
        "not known",
        "cannot be estimated",
        "frequency not known",
        "unknown frequency",
    },
}

SOC_PATTERNS = [
    r"infections?\s+and\s+infestations?",
    r"blood\s+and\s+lymphatic\s+system\s+disorders?",
    r"immune\s+system\s+disorders?",
    r"endocrine\s+disorders?",
    r"metabolism\s+and\s+nutrition\s+disorders?",
    r"psychiatric\s+disorders?",
    r"nervous\s+system\s+disorders?",
    r"eye\s+disorders?",
    r"ear\s+and\s+labyrinth\s+disorders?",
    r"cardiac\s+disorders?",
    r"vascular\s+disorders?",
    r"respiratory,?\s+thoracic\s+and\s+mediastinal\s+disorders?",
    r"gastrointestinal\s+disorders?",
    r"hepatobiliary\s+disorders?",
    r"skin\s+and\s+subcutaneous\s+tissue\s+disorders?",
    r"musculoskeletal\s+and\s+connective\s+tissue\s+disorders?",
    r"renal\s+and\s+urinary\s+disorders?",
    r"pregnancy,?\s+puerperium\s+and\s+perinatal\s+conditions?",
    r"reproductive\s+system\s+and\s+breast\s+disorders?",
    r"congenital,?\s+familial\s+and\s+genetic\s+disorders?",
    r"general\s+disorders?\s+and\s+administration\s+site\s+conditions?",
    r"investigations?",
    r"injury,?\s+poisoning\s+and\s+procedural\s+complications?",
    r"surgical\s+and\s+medical\s+procedures?",
    r"social\s+circumstances?",
]
